    - title: "CERN Summer School"
      url: "http://home.cern/"
      field: "Particle Physics"
      period: "Summer"
      retribution: "High"
      studies: "Undergraduate, Masters"
      region: "Switzerland"
      quality: "Excellent"
