    - title: "CERN Summer School"
      url: "http://home.cern/"
      field: "Particle Physics"
      period: "Summer"
      retribution: "High"
      studies: "Undergraduate, Masters"
      region: "Switzerland"
      quality: "Excellent"
      
      
     - title: "Astrophysics"
      url: "http://h"
      field: "Particl"
      period: "Sum"
      retribution: "High"
      studies: "Undeaduate, Masters"
      region: "Switd"
      quality: "Exclent"
